### PR TITLE
Communication: move Bullhorn to Forum bullet list

### PR DESCRIPTION
**Pull request by Andersson007**
Communication: move Bullhorn to Forum bullet list

### CODE REVIEW

**Comment by Andersson007** [comment]
I think @oraNod 's suggestion about moving Bullhorn to the forum list is fair that it's now a part of the forum.
cc @samccann

**Comment by oraNod** [comment]
@Andersson007 I still see the link to the html docs for the bullhorn. Why not change the url to https://forum.ansible.com/c/news/bullhorn/17

That will take folks directly to the bullhorn where they can subscribe or read old posts. I guess with the html docs they do get some usage details but it requires an extra hop to get to the content you really care about (i.e. bullhorn posts).

**Comment by Andersson007** [comment]
> @Andersson007 I still see the link to the html docs for the bullhorn. Why not change the url to https://forum.ansible.com/c/news/bullhorn/17
> 
> That will take folks directly to the bullhorn where they can subscribe or read old posts. I guess with the html docs they do get some usage details but it requires an extra hop to get to the content you really care about (i.e. bullhorn posts).

@oraNod i'm a bit concerned about maintainers not using bullhorn because w/o the reference to the docs they will not know how to do it. Extra hops are not good but can we allow it in this particular case?

**Comment by oraNod** [comment]
> > @Andersson007 I still see the link to the html docs for the bullhorn. Why not change the url to https://forum.ansible.com/c/news/bullhorn/17
> > That will take folks directly to the bullhorn where they can subscribe or read old posts. I guess with the html docs they do get some usage details but it requires an extra hop to get to the content you really care about (i.e. bullhorn posts).
> 
> @oraNod i'm a bit concerned about maintainers not using bullhorn because w/o the reference to the docs they will not know how to do it. Extra hops are not good but can we allow it in this particular case?

Yep. It's fine with me but always good to discuss and get aligned about the url. I'll do the same in the PRs I'm working on. Cheers.

**Review by samccann — APPROVED** [review]

**Comment by Andersson007** [comment]
@oraNod @samccann thanks for reviewing!

**Pull request merged**
